features_dim: 256

conv_layers:
  - out_channels: 32
    kernel_size: 8
    stride: 4
    norm:
      type: group
      num_groups: 8

  - out_channels: 64
    kernel_size: 4
    stride: 2
    norm:
      type: group
      num_groups: 8

  - out_channels: 64
    kernel_size: 3
    stride: 1
    norm:
      type: group
      num_groups: 8
